core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^test-404/$', 'core.views.error404'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/map/$', views.events_map, name='events_map'),
    url(r'^events/calendar.ics$', views.events_ical, name='icalendar'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^foundation/$', views.foundation, name='foundation'),
    url(r'^foundation/governing-document/$', views.governing_document,
        name='foundation-governing-document'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^2015/$', views.year_2015, name='year_2015'),
    url(r'^terms-conditions/$', views.terms_conditions, name='terms-conditions'),
    url(r'^privacy-cookies/$', views.privacy_cookies, name='privacy-cookies'),
    url(r'^workshop-box/$', views.workshop_box, name='workshop-box'),

    url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
    url(r'^$', views.index, name='index'),
]

djangogirls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Admin link for password reset
    # See: https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/login.html#L61
    url(r'^admin/password_reset/$',
        RedirectView.as_view(url='/account/password_reset', permanent=True),
        name='admin_password_reset'),

    # Regular links:
    url(r'^community/', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'', include('applications.urls', namespace='applications')),
    url(r'', include('core.urls', namespace='core')),
]

jobs/urls.py
from django.conf.urls import url

from jobs import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^meetups$', views.meetups, name='meetups'),
    url(r'^job/(?P<id>\d+)$', views.job_details, name='job_details'),
    url(r'^confirm_submission$', views.confirm_submission,
        name='confirm_submission'),
    url(r'^meetup/(?P<id>\d+)$', views.meetup_details, name='meetup_details'),
    url(r'^job/new$', views.create_job, name='job_new'),
    url(r'^meetup/new$', views.create_meetup, name='meetup_new'),
]

templates/global/base.html
{% load staticfiles rev %}
<!DOCTYPE HTML>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <title>{% block title %}Django Girls - start your journey with programming{% endblock %}</title>
  <meta name="description" content="{% block description %}Django Girls is a one-day workshop about programming in Python and Django for women.{% endblock %}">
  <meta name="keywords" content="programming, python, django, workshop, women, females">
  <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="{% block og_title %}Django Girls is a one-day workshop about programming in Python and Django for women{% endblock %}" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="{% block og_description %}Join us and become a female developer! Build your first website in Python and Django in a friendly, safe environment.{% endblock %}" />
  <meta property="og:image" content="{% block og_image %}https://raw.githubusercontent.com/olasitarska/djangogirls/gh-pages/resources/graphics/logo_square.png{% endblock %}" />

  <link rel="stylesheet" href="//brick.a.ssl.fastly.net/Lora:400,700,400i,700i/Roboto:300,400,300i,400i">
  {% block main_stylesheet %}<link rel="stylesheet" type="text/css" href="{% static_rev 'css/global.css' %}" media="screen">{% endblock %}

  <script type="text/javascript" src="{% static 'vendor/js/jquery.min.js' %}"></script>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.9/mapbox.js'></script>
  <script type="text/javascript" src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendor/js/sss.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</head>
<body>
    <div class="page-wrap">
        {% block menu %}
            {% include 'global/menu.html' %}
        {% endblock %}

        {% block content %}{% endblock %}
    </div>

    {% block footer %}
        {% include 'global/footer.html' %}
    {% endblock %}

    {% include 'includes/js.html' %}
</body>
</html>

templates/global/footer.html
<footer>
    <div class="container">
        <div class="row">

            <div class="col-md-2">
                <p>Django Girls</p>
                <ul>
                    <li><a href="{% url 'core:faq' %}">FAQ</a></li>
                    <li><a href="{% url 'core:foundation' %}">Foundation</a></li>
                    <li><a href="{% url 'core:newsletter' %}">Newsletter</a></li>
                    <li><a href="http://gitter.im/DjangoGirls/tutorial"><strong>Chat with us!</strong></a></li>
                    <li><a href="/pages/coc/">Code of Conduct</a></li>
                    <li><a href="{% url 'core:contact' %}">Contact</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>Support us</p>
                <ul>
                    <li><a href="{% url 'core:donate' %}">Make a donation</a></li>
                    <li><a href="https://www.patreon.com/djangogirls">Donate on Patreon</a></li>
                    <li><a href="{% url 'core:contribute' %}">Contribute</a></li>
                    <li><a href="https://www.stickermule.com/user/1068790133/stickers">Buy a sticker</a></li>
                    <li><a href="http://bit.ly/sponsordg">Sponsor us</a></li>
                </ul>
            </div>
            <div class="col-md-2">
                <p><a href="{% url 'jobs:main' %}">Community</a></p>
                <ul>
                    <li><a href="{% url 'jobs:jobs' %}">Job opportunities</a></li>
                    <li><a href="{% url 'jobs:meetups' %}">Meetups</a></li>
                    <li><a href="http://facebook.com/djangogirls">Facebook</a></li>
                    <li><a href="http://twitter.com/djangogirls">Twitter</a></li>
                    <li><a href="http://github.com/djangogirls">Github</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>Resources</p>
                <ul>
                    <li><a href="http://tutorial.djangogirls.org/">Tutorial</a></li>
                    <li><a href="http://organize.djangogirls.org/">Organizer's Manual</a></li>
                    <li><a href="http://coach.djangogirls.org/">Coaching Guide</a></li>
                    <li><a href="http://djangogirls.gitbooks.io/django-girls-tutorial-extensions/">Tutorial Extensions</a></li>
                    <li><a href="https://github.com/DjangoGirls/resources">Graphics</a></li>
                </ul>
            </div>

             <div class="col-md-2">
                <p>Website</p>
                <ul>
                    <li><a href="{% url 'core:terms-conditions' %}">Terms & Conditions</a></li>
                    <li><a href="{% url 'core:privacy-cookies' %}">Privacy & Cookies</a></li>
                </ul>
            </div>

            <div class="col-md-2">
                <p>♥</p>
                <ul>
                    <li><b>{{ future_events_count }}</b> upcoming events</li>
                    <li><b>{{ past_events_count }}</b> past events</li>
                    <!--- tags to do for job opportunities -->
                    <li><b>{{ meetup_count|default_if_none:'0' }}</b> upcoming meetups</li>
                    <li><b>{{ applicants_sum|default_if_none:'0' }}</b> applicants</li>
                    <li><b>{{ attendees_sum|default_if_none:'0' }}</b> attendees</li>
                    <li><b>{{ countries_count }}</b> countries</li>
                </ul>
            </div>

        </div>
    </div>
</footer>

templates/global/menu.html
{% load staticfiles %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav role="navigation" class="clearfix">
                <div class="logo">
                    <a href="/">
                        <img src="{% static 'img/global/logo.png' %}" alt="Django Girls" />
                    </a>
                </div>

                <ul>
                    <li><a href="{% url 'core:events' %}">Events</a></li>
                    <li><a href="{% url 'core:resources' %}">Resources</a></li>
                    <li><a href="{% url 'core:organize' %}">Organize</a></li>
                    <li><a href="{% url 'core:newsletter' %}">Newsletter</a></li>
                    <li><a href="http://blog.djangogirls.org/">Blog</a></li>
                    <li><a href="{% url 'core:contribute' %}">Contribute</a></li>
                    <li><a href="https://www.patreon.com/djangogirls">Support us</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>