applications/urls.py
from django.conf.urls import url

from applications import views
urlpatterns = [
    url(r'^(?P<city>[\w\d/]+)/apply/$', views.apply, name='apply'),
    url(r'^(?P<city>[\w\d/]+)/applications/$',
        views.applications, name='applications'),
    url(r'^(?P<city>[\w\d/]+)/applications/(?P<app_number>\d+)$',
        views.application_detail, name='application_detail'),
    url(r'^(?P<city>[\w\d/]+)/applications/change_state/$',
        views.change_state, name='change_state'),
    url(r'^(?P<city>[\w\d/]+)/applications/change_rsvp/$',
        views.change_rsvp, name='change_rsvp'),
    url(r'^(?P<city>[\w\d/]+)/applications/download/$',
        views.applications_csv, name='applications_csv'),
    url(r'^(?P<city>[\w\d/]+)/communication/$',
        views.communication, name='communication'),
    url(r'^(?P<city>[\w\d/]+)/communication/compose/$',
        views.compose_email, name='compose_email'),
    url(r'^(?P<city>[\w\d/]+)/communication/compose/(?P<email_id>\d+)$',
        views.compose_email, name='compose_email'),
    url(r'^(?P<city>[\w\d/]+)/rsvp/(?P<code>[\w\d/]+)$',
        views.rsvp, name='rsvp'),
]

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^test-404/$', 'core.views.error404'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/map/$', views.events_map, name='events_map'),
    url(r'^events/calendar.ics$', views.events_ical, name='icalendar'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^foundation/$', views.foundation, name='foundation'),
    url(r'^foundation/governing-document/$', views.governing_document,
        name='foundation-governing-document'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^2015/$', views.year_2015, name='year_2015'),
    url(r'^terms-conditions/$', views.terms_conditions, name='terms-conditions'),
    url(r'^privacy-cookies/$', views.privacy_cookies, name='privacy-cookies'),
    url(r'^workshop-box/$', views.workshop_box, name='workshop-box'),

    url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
    url(r'^$', views.index, name='index'),
]

djangogirls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Admin link for password reset
    # See: https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/login.html#L61
    url(r'^admin/password_reset/$',
        RedirectView.as_view(url='/account/password_reset', permanent=True),
        name='admin_password_reset'),

    # Regular links:
    url(r'^community/', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'', include('applications.urls', namespace='applications')),
    url(r'', include('core.urls', namespace='core')),
]

applications/models.py
import random
import string

from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.mail import EmailMessage
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from core.models import EventPage, User
from .utils import DEFAULT_QUESTIONS


QUESTION_TYPES = (
    ('paragraph', 'Paragraph'),
    ('text', 'Long text'),
    ('choices', 'Choices'),
    ('email', 'Email')
)

APPLICATION_STATES = (
    ('submitted', 'Application submitted'),
    ('accepted', 'Application accepted'),
    ('rejected', 'Application rejected'),
    ('waitlisted', 'Application on waiting list'),
    ('declined', 'Applicant declined'),
)

RSVP_STATUSES = (
    ('waiting', 'RSVP: Waiting for response'),
    ('yes', 'RSVP: Confirmed attendance'),
    ('no', 'RSVP: Rejected invitation')

)

RSVP_LINKS = ['[rsvp-url-yes]', '[rsvp-url-no]']


@python_2_unicode_compatible
class Form(models.Model):
    page = models.ForeignKey(EventPage, null=False, blank=False, unique=True)
    text_header = models.CharField(
        max_length=255, default="Apply for a spot at Django Girls [City]!")
    text_description = models.TextField(
        default="Yay! We're so excited you want to be a part of our "
        "workshop. Please mind that filling out the form below does "
        "not give you a place on the workshop, but a chance to get "
        "one. The application process is open from {INSERT DATE} "
        "until {INSERT DATE}. If you're curious about the criteria "
        "we use to choose applicants, you can read about it on "
        "<a href='http://blog.djangogirls.org/post/91067112853/"
        "djangogirls-how-we-scored-applications'>Django Girls "
        "blog</a>. Good luck!")
    confirmation_mail = models.TextField(
        default="Hi there!"
        "This is a confirmation of your application to <a href=\"http://djangogirls.org/{city}\">Django Girls {CITY}</a>. "
        "Yay! That's a huge step already, we're proud of you!\n\n"
        "Mind that this is not a confirmation of participation in the event, but a confirmation that we received your application.\n\n"
        "You'll receive an email from the team that organizes Django Girls {CITY} soon. "
        "You can always reach them by answering to this email or by writing to {your event mail}.\n"
        "For your reference, we're attaching your answers below.\n\n"
        "Hugs, cupcakes and high-fives!\n"
        "Django Girls",
        help_text="Mail will be sent from your event mail.\nAlso the answers will be attached.")
    open_from = models.DateTimeField(
        null=True, verbose_name="Application process is open from")
    open_until = models.DateTimeField(
        null=True, verbose_name="Application process is open until")

    def __str__(self):
        return 'Application form for {}'.format(self.page.event.name)

    def save(self, *args, **kwargs):
        is_form_new = False if self.pk else True
        super(Form, self).save(*args, **kwargs)

        if is_form_new:
            self.create_default_questions()

    def create_default_questions(self):
        i = 1
        for question in DEFAULT_QUESTIONS:
            question['form'] = self
            question['order'] = i
            Question.objects.create(**question)
            i += 1

    @property
    def number_of_applications(self):
        return self.application_set.count()

    @property
    def application_open(self):
        if self.open_from and self.open_until:
            return (self.open_from < timezone.now() < self.open_until)
        return True


@python_2_unicode_compatible
class Question(models.Model):
    form = models.ForeignKey(Form, null=False, blank=False)
    title = models.TextField(verbose_name="Question")
    help_text = models.TextField(
        blank=True, default='', verbose_name="Additional help text to the question?")
    question_type = models.CharField(
        max_length=50,
        choices=QUESTION_TYPES, verbose_name="Type of the question")
    is_required = models.BooleanField(
        default=True, verbose_name="Is the answer to the question required?")
    choices = models.TextField(
        blank=True, default='', verbose_name="List all available options, separated with semicolon (;)",
        help_text="Used only with 'Choices' question type")
    is_multiple_choice = models.BooleanField(
        default=False, verbose_name="Are there multiple choices allowed?",
        help_text="Used only with 'Choices' question type")
    order = models.PositiveIntegerField(
        null=False, blank=False, help_text="Position of the question")

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.title

    def get_choices_as_list(self):
        if self.question_type != 'choices':
            raise TypeError(
                "You can only get choices for fields that have"
                " question_type == choices."
            )

        return self.choices.split(';')


@python_2_unicode_compatible
class Application(models.Model):
    form = models.ForeignKey(Form, null=False, blank=False)
    number = models.PositiveIntegerField(default=1, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    state = models.CharField(
        max_length=50,
        choices=APPLICATION_STATES, verbose_name="State of the application",
        null=True,
        default='submitted'
    )
    email = models.EmailField(null=True, blank=True)
    newsletter_optin = models.BooleanField(default=False)

    rsvp_status = models.CharField(
        max_length=50,
        choices=RSVP_STATUSES, verbose_name="RSVP status",
        default='waiting'
    )
    rsvp_yes_code = models.CharField(max_length=24, null=True)
    rsvp_no_code = models.CharField(max_length=24, null=True)

    def save(self, *args, **kwargs):
        if self.pk is None:
            current_max = Application.objects.filter(form=self.form).aggregate(models.Max('number'))['number__max']
            self.number = (current_max or 0) + 1
        super(Application, self).save(*args, **kwargs)

    @property
    def average_score(self):
        """
        Return the average score for this Application.
        """
        scores = [s.score for s in self.scores.all() if (s.score and s.score > 0)]
        if not scores:
            return 0
        else:
            return sum(scores) / float(len(scores))

    def variance(self):
        data = [s.score for s in self.scores.all() if s.score]
        n = len(data)
        if n == 0:
            return 0
        c = sum(data) / float(len(data))
        if n < 2:
            return 0
        ss = sum((x-c)**2 for x in data)
        ss -= sum((x-c) for x in data)**2/len(data)
        assert not ss < 0, 'negative sum of square deviations: %f' % ss
        return ss / (n-1)

    def stdev(self):
        return self.variance() ** 0.5

    def generate_code(self):
        return ''.join([random.choice(string.ascii_letters + string.digits) for i in range(24)])

    def get_rsvp_yes_code(self):
        if not self.rsvp_yes_code:
            self.rsvp_yes_code = self.generate_code()
            self.save()
        return self.rsvp_yes_code

    def get_rsvp_no_code(self):
        if not self.rsvp_no_code:
            self.rsvp_no_code = self.generate_code()
            self.save()
        return self.rsvp_no_code

    @classmethod
    def get_by_rsvp_code(self, code, page):
        """ Returns application and RSVP status or None """
        try:
            application = self.objects.get(rsvp_yes_code=code, form__page=page)
            return application, 'yes'
        except self.DoesNotExist:
            try:
                application = self.objects.get(rsvp_no_code=code, form__page=page)
                return application, 'no'
            except self.DoesNotExist:
                return None, None
        return None, None

    @property
    def is_accepted(self):
        return self.state == 'accepted'

    def is_scored_by_user(self, user):
        """
        Returns true if the given user has scored this application
        or false if they have not, or there is a zero score.
        """
        return self.scores.filter(user=user, score__gt=0).exists()

    def __str__(self):
        return str(self.pk)


class Answer(models.Model):
    application = models.ForeignKey(Application, null=False, blank=False)
    question = models.ForeignKey(Question, null=False, blank=False)
    answer = models.TextField()

    class Meta:
        ordering = ('question__order',)


class Score(models.Model):
    """
    A score represents the score given by a coach for an application.
    """

    user = models.ForeignKey(User, related_name='scores')
    application = models.ForeignKey(Application, related_name='scores')
    score = models.FloatField(
        help_text='5 being the most positive, 1 being the most negative.',
        validators=[MaxValueValidator(5), MinValueValidator(0)], 
        default=0
    )
    comment = models.TextField(
        null=True, blank=True, help_text='Any extra comments?')

    class Meta:
        unique_together = ('user', 'application',)


@python_2_unicode_compatible
class Email(models.Model):
    form = models.ForeignKey(Form)
    author = models.ForeignKey(User, related_name="author")
    subject = models.CharField(max_length=255)
    text = models.TextField(
        verbose_name="Content of the email",
        help_text="You can use HTML syntax in this message. Preview on the right."
    )
    recipients_group = models.CharField(
        max_length=50, choices=APPLICATION_STATES+RSVP_STATUSES,
        verbose_name="Recipients",
        help_text="Only people assigned to chosen group will receive this email."
    )
    number_of_recipients = models.IntegerField(default=0, null=True)
    successfuly_sent = models.TextField(null=True, blank=True)
    failed_to_sent = models.TextField(null=True, blank=True)

applications/forms.py
from django import forms
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.conf import settings
from captcha.fields import ReCaptchaField
import requests
import hashlib


from .models import Application, Answer, Question, Score, Email
from .utils import generate_form_from_questions
from core.forms import BetterReCaptchaField


class ApplicationForm(forms.Form):

    def __init__(self, *args, **kwargs):
        """
        The form here is programatically generated out of Question objects
        """

        questions = kwargs.pop('questions')
        super(ApplicationForm, self).__init__(*args, **kwargs)
        self.fields = generate_form_from_questions(questions)
        self.fields['captcha'] = BetterReCaptchaField()


    def save(self, *args, **kwargs):
        form = kwargs.pop('form')
        application = Application.objects.create(form=form)

        for name in self.cleaned_data:
            question = None
            pk = name.replace('question_', '')
            value = self.cleaned_data[name]
            try:
                question = Question.objects.get(pk=pk, form=form)
            except (Question.DoesNotExist, ValueError):
                if name == 'newsletter_optin':
                    if value == 'yes':
                        application.newsletter_optin = True
                    else:
                        application.newsletter_optin = False
                    application.save()

            value = ', '.join(value) if type(value) == list else value

            if question:
                Answer.objects.create(
                    application=application,
                    question=question,
                    answer=value
                )

                if question.question_type == 'email':
                    application.email = value
                    application.save()

        if not form.page.event.email:
            # If event doesn't have an email (legacy events), create
            # it just by taking the url. In 99% cases, it is correct.
            form.page.event.email = "{}@djangogirls.org".format(form.page.url)
            form.page.event.save()

        if application.email:
            # Send confirmation email
            subject = "Confirmation of your application for {}".format(form.page.title)
            body = render_to_string(
                'emails/application_confirmation.html',
                {
                    'application': application,
                    'intro': form.confirmation_mail,
                }
            )
            msg = EmailMessage(subject, body, form.page.event.email, [application.email,])
            msg.content_subtype = "html"
            try:
                msg.send()
            except:
                # TODO: what should we do when sending fails?
                pass

        # Adding applicant email to Django Girls Dispatch
        if application.newsletter_optin and application.email:
            emailb = application.email.encode()
            emailhash = hashlib.md5(emailb).hexdigest()
            r = requests.get("https://us8.api.mailchimp.com/3.0/lists/d278270e6f/members/%s" %emailhash, auth=('user', settings.MAILCHIMP_API_KEY))
            # Mailchimp will return a 404 if the email we want to add is not on the Dispatch subscriber list
            if r.status_code == 404:
                url = "https://us8.api.mailchimp.com/3.0/lists/d278270e6f/members/"
                payload = {"email_address" : application.email, "status": "pending"}
                requests.post(url, auth=('user', settings.MAILCHIMP_API_KEY), json=payload)

class ScoreForm(forms.ModelForm):

    class Meta:
        model = Score
        fields = ['score', 'comment']


class EmailForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        """
        When email is already sent, the form should be disabled
        """
        super(EmailForm, self).__init__(*args, **kwargs)
        if self.instance.sent:
            # email was sent, let's disable all fields:
            for field in self.fields:
                self.fields[field].widget.attrs['disabled'] = True

    class Meta:
        model = Email
        fields = ['recipients_group', 'subject', 'text']

templates/applications/application_detail.html
{% extends 'core/event.html' %}
{% load static %}

{% block title %}{{ page.title }}{% endblock %}
{% block description %}{{ page.description }}{% endblock %}

{% block content %}

<div class="container without-background">
    <div class="row">
        <div class="col-md-12 applications">
            <h3 class="page-header">Application #{{ application.number }} for {{ page.title }}</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-md-7 applications">
        {% for answer in application.answer_set.all %}
            <div class="answer">
                <p class="question">{{ answer.question.title|safe }}</p>
                <p>{{ answer.answer|urlize|linebreaks }}</p>
            </div>
        {% endfor %}
        </div>


        <div class="col-md-5 scoring">
            {% if user_score.score > 0 %}
            <h4>Scores</h4>
            <ul>
                <li>Average score: {{ application.average_score }}</li>
                <li>Your score: {{ user_score.score }}</li>
            </ul>
            <table>
                <thead>
                    <td>Person</td>
                    <td>Score</td>
                    <td>Comment</td>
                </thead>
                {% for s in scores %}
                <tr>
                    <td>{{ s.user }}</td>
                    <td>{{ s.score }}</td>
                    <td>{{ s.comment }}</td>
                </tr>
                {% endfor %}
            </table>
            {% endif %}

            <h4>Your score</h4>
            <form action="" method="post" class="scoring-form">
                {% csrf_token %}
                {% with score_form as form %}
                    {% include 'includes/_form.html' %}
                {% endwith %}
                <input class="btn" type="submit" value="Save" />
                <input class="btn" type="submit" name="random" value="Save & go to next" />
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/applications/applications.html
{% extends 'core/event.html' %}
{% load static applications_tags rev %}

{% block custom_js %}<script type="text/javascript" src="{% static_rev 'js/applications.js' %}"></script>{% endblock %}

{% block title %}{{ page.title }}{% endblock %}
{% block description %}{{ page.description }}{% endblock %}

{% block content %}

<div id="applications"
     data-change-state-url="{% url 'applications:change_state' page.url %}"
     data-change-rsvp-url="{% url 'applications:change_rsvp' page.url %}"
></div>

<div class="container">
  <form action="{% url 'applications:change_state' page.url %}" method="post" id="change-state-form">
  <div class="row">
    <div class="col-md-12 applications">
      <h3 class="page-header">Applications for {{ page.title }}</h3>
      {% if applications %}
          <p>
              Filter:
              <a href="?{% if order %}order={{ order }}{% endif %}">All</a> |
              <a href="?state=submitted{% if order %}&order={{ order }}{% endif %}" class="text-primary">Submitted</a> |
              <a href="?state=accepted{% if order %}&order={{ order }}{% endif %}" class="text-success">Accepted</a> |
              <a href="?state=rejected{% if order %}&order={{ order }}{% endif %}" class="text-danger">Rejected</a> |
              <a href="?state=waitlisted{% if order %}&order={{ order }}{% endif %}" class="text-warning">Waiting list</a> |
              <a href="?state=declined{% if order %}&order={{ order }}{% endif %}" class="text-danger">Declined</a> |
              <a href="?rsvp_status=waiting{% if order %}&order={{ order }}{% endif %}" class="text-primary">RSVP: waiting</a> |
              <a href="?rsvp_status=yes{% if order %}&order={{ order }}{% endif %}" class="text-success">RSVP: confirmed</a> |
              <a href="?rsvp_status=no{% if order %}&order={{ order }}{% endif %}" class="text-danger">RSVP: rejected</a>
          </p>
          <p>Change the status of selected applications to:
              <select name="state">
                  <option value="" selected>Choose status</option>
                  <option value="submitted">Application submitted</option>
                  <option value="accepted">Application accepted</option>
                  <option value="rejected">Application rejected</option>
                  <option value="waitlisted">Application on waiting list</option>
                  <option value="declined">Applicant declined</option>
              </select>
              <input type="submit" value="Apply" />
          </p>
          <a href="{% url 'applications:applications_csv' page.url %}{{ active_query_string }}" class="btn download">Download to csv</a>
          <p>Showing {{ applications|length }} application{{ applications|length|pluralize }} out of {{ all_applications_count }}, selected: <span id="selected-count">0</span></p>
          <table class="table">
              <thead>
                  <tr>
                      <th><input type="checkbox" name="application" id="select-all-box" /></th>
                      <th>#</th>
                      <th>E-mail</th>
                      <th>Application status</th>
                      <th>RSVP</th>
                      <th>Score {% display_sorting_arrow 'average_score' order %}</th>
                      <th>&nbsp;</th>
                  </tr>
              </thead>
              <tbody>
                  {% for app in applications %}
                  <tr>
                      <td>
                        <input type="checkbox"
                               name="application"
                               class="application-box"
                               value="{{ app.id }}"
                               id="application-{{ app.id }}-box" />
                      </td>
                      <td><a href="{% url 'applications:application_detail' city=app.form.page.url app_number=app.number %}">{{ app.number }}</a></td>
                      <td>{{ app.email|default:"No email" }}</td>
                      <td>
                          <div class="dropdown">
                            <button
                                class="btn btn-default dropdown-toggle {{ app.state|default:'default' }}"
                                type="button"
                                id="application-{{ app.id }}-state"
                                data-toggle="dropdown"
                              >
                              {{ app.get_state_display }}
                              <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                              <li><a href="#" class="state-change" data-state="submitted" data-app-id="{{ app.id }}">Application submitted</a></li>
                              <li><a href="#" class="state-change" data-state="accepted" data-app-id="{{ app.id }}">Application accepted</a></li>
                              <li><a href="#" class="state-change" data-state="rejected" data-app-id="{{ app.id }}">Application rejected</a></li>
                              <li><a href="#" class="state-change" data-state="waitlisted" data-app-id="{{ app.id }}">Application on waiting list</a></li>
                              <li><a href="#" class="state-change" data-state="declined" data-app-id="{{ app.id }}"> Applicant declined</a></li>
                            </ul>
                          </div>
                      </td>
                      <td>
                        {% if app.is_accepted %}
                          <div class="dropdown">
                            <button
                                class="btn btn-default dropdown-toggle {{ app.rsvp_status|default:'default' }}"
                                type="button"
                                id="application-{{ app.id }}-rsvp-status"
                                data-toggle="dropdown"
                              >
                              {{ app.get_rsvp_status_display }}
                              <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                              <li><a href="#" class="rsvp-change" data-rsvp="waiting" data-app-id="{{ app.id }}">Waiting for response</a></li>
                              <li><a href="#" class="rsvp-change" data-rsvp="yes" data-app-id="{{ app.id }}">Confirmed attendance</a></li>
                              <li><a href="#" class="rsvp-change" data-rsvp="no" data-app-id="{{ app.id }}">Rejected invitation</a></li>
                            </ul>
                          </div>
                        {% else %}
                          —
                        {% endif %}
                      </td>
                      <td>
                          {% if app|scored_by_user:request.user %}
                              {{ app.average_score }}
                              <span class="num_votes">({{ app.scores.count }} vote{{ app.scores.count|pluralize }}, &sigma;={{ app.stdev|floatformat:"1" }})</span>
                          {% else %}
                              (hidden)
                          {% endif %}
                      </td>
                      <td class="text-right">
                          <a href="{% url 'applications:application_detail' city=app.form.page.url app_number=app.number %}" class="btn">View Application</a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
      {% else %}
          <p class="lead">Nothing to see here...</p>
      {% endif %}
    </div>
  </div>
  </form>
</div>
{% endblock %}

templates/applications/communication.html
{% extends 'core/event.html' %}
{% load static applications_tags rev %}

{% block custom_js %}<script type="text/javascript" src="{% static_rev 'js/applications.js' %}"></script>{% endblock %}

{% block title %}{{ page.title }}{% endblock %}
{% block description %}{{ page.description }}{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12 applications">
      <h3 class="page-header">
        Send email to applicants of {{ page.title }}
        <a class="btn pull-right" href="{% url 'applications:compose_email' page.url %}">Create new e-mail</a>
      </h3>

      <table class="table">
          <thead>
              <tr>
                  <th>Subject</th>
                  <th>Recipients</th>
                  <th>Status</th>
                  <th>Sent</th>
                  <th>&nbsp;</th>
              </tr>
          </thead>
          <tbody>
              {% if emails %}
                {% for email in emails %}
                <tr>
                    <td><a href="{% url 'applications:compose_email' page.url email.id %}">{{ email.subject }}</a></td>
                    <td>{{ email.get_recipients_group_display }}</td>
                    <td><span class="label label-{% if email.sent %}success">Sent{% else %}default">Draft{% endif %}</span></td>
                    <td>{{ email.sent|default:"−" }}</td>
                    <td><a href="{% url 'applications:compose_email' page.url email.id %}" class="btn pull-right">View message</a></td>
                </tr>
                {% endfor %}
              {% else %}
                <tr>
                    <td colspan="6">No messages yet. <a href="{% url 'applications:compose_email' page.url %}">Create one!</a></td>
                </tr>
              {% endif %}
          </tbody>
      </table>

    </div>
  </div>
</div>
{% endblock %}

templates/applications/event_not_live.html
{% extends 'global/base.html' %}

{% block content %}

        <div class="container">

            <div class="row">
                <div class="col-md-12">
                    <h2>{{ city|title }}</h2>
                    {% if past %}
                        <p>The event for {{ city|title }} has already happened and the webpage is
                        no longer live.</p>
                    {% else %}
                        <p>The event page for {{ city|title }} will be coming soon.</p>
                    {% endif %}
                    <p>If you want to contact the organizers of this
                    event, you can email them at
                        <a href="mailto:{{ city }}@djangogirls.org">{{ city|lower }}@djangogirls.org</a></p>


                    <h3>See all other <a href="{% url 'core:events' %}">upcoming events</a>.</h3>
                </div>
            </div>


    </div>

{% endblock content %}