core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^test-404/$', 'core.views.error404'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/map/$', views.events_map, name='events_map'),
    url(r'^events/calendar.ics$', views.events_ical, name='icalendar'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^foundation/$', views.foundation, name='foundation'),
    url(r'^foundation/governing-document/$', views.governing_document,
        name='foundation-governing-document'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^2015/$', views.year_2015, name='year_2015'),
    url(r'^terms-conditions/$', views.terms_conditions, name='terms-conditions'),
    url(r'^privacy-cookies/$', views.privacy_cookies, name='privacy-cookies'),
    url(r'^workshop-box/$', views.workshop_box, name='workshop-box'),

    url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
    url(r'^$', views.index, name='index'),
]

djangogirls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Admin link for password reset
    # See: https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/login.html#L61
    url(r'^admin/password_reset/$',
        RedirectView.as_view(url='/account/password_reset', permanent=True),
        name='admin_password_reset'),

    # Regular links:
    url(r'^community/', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'', include('applications.urls', namespace='applications')),
    url(r'', include('core.urls', namespace='core')),
]

core/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms
from captcha.fields import ReCaptchaField

from .models import User, ContactEmail, Event


class BetterReCaptchaField(ReCaptchaField):
    """A ReCaptchaField that always works in DEBUG mode"""
    def clean(self, values):
        if settings.DEBUG:
            return values[0]
        return super(BetterReCaptchaField, self).clean(values)


class UserCreationForm(forms.ModelForm):
    error_messages = {
        'password_mismatch': "The two password fields didn't match.",
    }
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        help_text="Enter the same password as above, for verification."
    )

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = auth_forms.ReadOnlyPasswordHashField(
        label="Password",
        help_text="Raw passwords are not stored, so there is no way to see "
                  "this user's password, but you can change the password "
                  "using <a href=\"password/\">this form</a>.")

    class Meta:
        model = User
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(UserChangeForm, self).__init__(*args, **kwargs)
        f = self.fields.get('user_permissions', None)
        if f is not None:
            f.queryset = f.queryset.select_related('content_type')

    def clean_password(self):
        return self.initial["password"]


class UserLimitedChangeForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name')


class EventChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):
        return "{}, {}".format(obj.city, obj.country)


class ContactForm(forms.ModelForm):
    event = EventChoiceField(
        queryset=Event.objects.public().distinct('city', 'country').order_by('city'),
        required=False, label="Django Girls workshop in..."
    )
    captcha = BetterReCaptchaField()

    class Meta:
        model = ContactEmail
        fields = (
            'name',
            'email',
            'contact_type',
            'event',
            'message',
        )
        widgets = {'contact_type': forms.RadioSelect}

    def clean_event(self):
        contact_type = self.cleaned_data.get('contact_type')
        event = self.cleaned_data.get('event')
        if contact_type == ContactEmail.CHAPTER:
            if not event:
                raise forms.ValidationError('Please select the event')
        return event

core/views.py
import icalendar

from django.conf import settings
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django_date_extensions.fields import ApproximateDate

from .models import Event, EventPage, Story, ContactEmail, User
from .forms import ContactForm
from patreonmanager.models import FundraisingStatus


def index(request):

    return render(request, 'core/index.html', {
        'future_events': Event.objects.future().select_related('eventpage'),
        'stories': Story.objects.filter(is_story=True).order_by('-created')[:2],
        'blogposts': Story.objects.filter(is_story=False).order_by('-created')[:3],
        'patreon_stats': FundraisingStatus.objects.all().first(),
        'organizers_count': User.objects.all().count(),
        'cities_count': Event.objects.values('city').distinct().count(),
        'country_count': Event.objects.values('country').distinct().count(),
    })


def events(request):

    return render(request, 'core/events.html', {
        'future_events': Event.objects.future().select_related('eventpage'),
        'past_events': Event.objects.past().select_related('eventpage'),
    })


def events_map(request):

    return render(request, 'core/events_map.html', {
        'events': Event.objects.public().order_by('date'),
        'mapbox_map_id': settings.MAPBOX_MAP_ID,
    })


def resources(request):
    return render(request, 'core/resources.html', {})


def organize(request):
    return render(request, 'core/organize.html', {})


def stories(request):

    return render(request, 'core/stories.html', {
        'stories': Story.objects.filter(is_story=True).order_by('-created'),
    })


def event(request, city):
    now = timezone.now()
    now_approx = ApproximateDate(year=now.year, month=now.month, day=now.day)
    page = get_object_or_404(
        EventPage.objects.select_related('event'),
        url=city.lower()
    )

    if page.url != city:
        return redirect('core:event', city=page.url, permanent=True)

    can_show = request.user.is_authenticated() or 'preview' in request.GET
    if not page.is_live and not can_show:
        return render(
            request,
            'applications/event_not_live.html',
            {'city': city, 'past': page.event.date <= now_approx}
        )

    return render(request, "core/event.html", {
        'page': page,
        'menu': page.menu.all(),
        'content': page.content.prefetch_related('coaches', 'sponsors').filter(is_public=True),
    })


def events_ical(request):
    events = Event.objects.public().order_by('-date')
    calendar = icalendar.Calendar()
    calendar['summary'] = "List of Django Girls events around the world"
    for event in events:
        ical_event = event.as_ical()
        if ical_event is None:
            continue  # Skip events with an approximate date
        calendar.add_component(ical_event)

    return HttpResponse(calendar.to_ical(),
                        content_type='text/calendar; charset=UTF-8')


def newsletter(request):
    return render(request, 'core/newsletter.html', {})


def faq(request):
    return render(request, 'core/faq.html', {})


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            contact_email = form.save()
            if contact_email.sent_successfully:
                messages.add_message(
                    request,
                    messages.INFO,
                    "Thank you for your email. We will be in touch shortly."
                )
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    "Ooops. We couldn't send your email :( Please try again later"
                )
            return render(request, 'core/contact.html', {'form': ContactForm()})
    else:
        form = ContactForm()
    return render(request, 'core/contact.html', {'form': form})


def foundation(request):
    return render(request, 'core/foundation.html', {})


def governing_document(request):
    return render(request, 'core/governing_document.html', {})


def contribute(request):
    return render(request, 'core/contribute.html', {})


def donate(request):
    return render(request, 'core/donate.html', {})


def year_2015(request):
    return render(request, 'core/2015.html', {
        'events': Event.objects.public().filter(date__lt='2016-01-01').order_by('date'),
        'mapbox_map_id': settings.MAPBOX_MAP_ID,
    })

def terms_conditions(request):
    return render(request, 'core/terms_conditions.html', {})

def privacy_cookies(request):
    return render(request, 'core/privacy_cookies.html', {})
    

def workshop_box(request):
    return render(request, 'core/workshop_box.html', {})

templates/core/event.html
{% extends 'event/base.html' %}
{% load thumbnail %}

{% block title %}{{ page.title }}{% endblock %}
{% block description %}{{ page.description }}{% endblock %}
{% block custom_css %}
    <style>
        {{ page.custom_css|default_if_none:'' }}
    </style>
{% endblock %}

{% block content %}

    {% for item in content %}

        {% include 'includes/item.html' with item=item %}

    {% endfor %}

{% endblock %}

templates/core/events.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">

        <section id="events">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        Upcoming events
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:icalendar' %}">ICAL</a>
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:events_map' %}">MAP</a>
                    </h2>
                </div>
            </div>

            <div class="row">
                {% for event in future_events %}
                    {% include 'includes/_event.html' with event=event %}
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                {% endfor %}
            </div>

            <div class="row past-events">
                <div class="col-md-12">
                    <h2>Past events</h2>
                </div>
            </div>

            <div class="row">
                {% for event in past_events %}
                    {% include 'includes/_event.html' with event=event %}
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                {% endfor %}
            </div>

        </section>

        <section id="organize">
            {% include 'includes/_no_event.html' %}
        </section>

    </div>

{% endblock %}

templates/core/events_map.html
{% extends 'global/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <h2>Django Girls events</h2>
        <div id="map"></div>
    </div>
   
    <script>
        L.mapbox.accessToken = 'pk.eyJ1Ijoib2xhc2l0YXJza2EiLCJhIjoiZGUzZjUyNjUxYWNkOGU1ODBkYjcxNzc4MTllNGRlMjcifQ.t0yuSZmW5FvragLmVgJXNQ';
        var past = L.layerGroup()
        var future = L.layerGroup()
        var map = L.mapbox.map('map', '{{ mapbox_map_id }}', {scrollWheelZoom: false, layers: [past, future]}).setView([30, 0], 2);
        L.control.layers(null, {
          'Upcoming': future,
          'Past': past,
        }).addTo(map);

        {% for event in events %}
            {% if event.latlng %}
            L.marker([{{ event.latlng }}], {
                icon: L.mapbox.marker.icon({
                    'marker-size': 'medium',
                    'marker-symbol': 'heart',
                    'marker-color': '#{{ event.eventpage.main_color }}'
                })
              }).addTo(
                  {% if event.is_upcoming %}future{% else %}past{% endif %}
              ).bindPopup(
                  '{% if event.eventpage.is_live %}<a href="/{{ event.eventpage.url }}">{% endif %}{{ event.city }}, {{ event.country }}{% if event.eventpage.is_live %}</a>{% endif %}'
              );
            {% endif %}
        {% endfor %}
    </script>

{% endblock %}

templates/core/foundation.html
{% extends 'global/base.html' %}
{% load staticfiles markdown_deux_tags %}

{% block title %}Django Girls Foundation{% endblock %}

{% block content %}
    <div class="container without-background" id="flatpage">
          <div id="value" class="row">
              <div class="col-md-12">
                  <h1>Django Girls Foundation</h1>
                  {% markdown "trusted" %}
Django Girls Foundation is a Charitable Incorporated Organisation (“the CIO”). The goal of the foundation is to advance the education of the public in particular but not exclusively women in the subject of computer science by providing or assisting in the provision of programming workshops and educational material.

The foundation achieves that by:

- providing opportunities, such as free, accessible programming workshops for women and creating educational materials available online;
- promoting the image of female software engineer by driving advertising campaigns to encourage women to join the IT field and highlighting existing role models.

The Django Girls Foundation is a legal entity protecting Django Girls, but **it is not Django Girls initiative itself**. Django Girls term could be used by anyone involved with Django Girls community and being a trustee is not required.

## Foundation details

**Official name:** Django Girls Foundation

**Other names:** Django Girls Foundation of Awesome, Cupcake and Emoji, DGF, DGFACE, 🐶

**Registered Charity Number:** [1163260](http://apps.charitycommission.gov.uk/Showcharity/RegisterOfCharities/CharityFramework.aspx?RegisteredCharityNumber=1163260&SubsidiaryNumber=0)

[Charity Certificate of Registration is available here](https://drive.google.com/file/d/0B-eUYObdf2QbUTVtb2cwU2M1M00/view?usp=sharing)

[Governing document is available here]({% url 'core:foundation-governing-document' %}).

**Address:**
United House,
North Road,
London N7 9DP,
United Kingdom

### Trustees

- Baptiste Mispelone
- Aleksandra Sendecka
- Aleksandra Sitarska
- Anna Warzecha

## Who owns Django Girls?

The Django Girls Foundation and **the community**.

## How can I financially support Django Girls Foundation?

There are several ways to financially support Django Girls Foundation:

- you could support us on [Patreon](https://www.patreon.com/djangogirls) by monthly donations.
- sponsoring one of [Django Girls events]({% url 'core:events' %}), by contacting local organizers.

## More information

If you want to learn more about Django Girls Foundation or have a question about the foundation, you can contact us by writing an e-mail to [foundation@djangogirls.org](mailto:foundation@djangogirls.org).
                  {% endmarkdown %}
              </div>
          </div>
    </div>
{% endblock %}

templates/core/index.html
{% extends 'global/base.html' %}
{% load staticfiles rev %}

{% block extra_js %}
    <script type="text/javascript" src="{% static_rev 'js/global.js' %}"></script>
{% endblock %}

{% block content %}

    <section id="box-with-picture">
      <div class="black-canvas">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1>
                        We inspire women to fall in love with programming.
                    </h1>
                    <p>
                        Django Girls organize free Python and Django workshops, create open sourced online tutorials and curate amazing first experiences with technology.
                    </p>
                </div>
            </div>
        </div>
      </div>
    </section>

    <div class="container">
        <section id="about">
            <div class="row">
                <div class="col-md-6">
                    <h2>What is Django Girls?</h2>
                    <p>
                        Django Girls is a <a href="{% url 'core:foundation' %}">non-profit organization</a> and a community that empowers and helps women to organize free, one-day programming workshops by providing tools, resources and support. We are a volunteer run organization with hundreds of people contributing to bring more amazing women into the world of technology. We are making technology more approachable by creating simpler tools and resources designed with empathy.
                    </p>
                    <p>
                        During each of our events, 30-60 women build their first web application using HTML, CSS, Python and Django.
                    </p>
                    {# <p><a href="">Learn more about Django Girls »</a></p> #}
                </div>
                <div class="col-md-6">
                  <iframe src="//player.vimeo.com/video/112325567?title=0&amp;byline=0&amp;portrait=0&amp;color=ff9933" width="585" height="329" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <h2>Django Girls impact</h2>
                    <p>
                        Since 2014, an army of <span class="highlighted-number">{{ organizers_count|default_if_none:'0' }} volunteers</span> in the Django Girls community organized <span class="highlighted-number">{{ all_events_count|default_if_none:'0' }} events.</span> We've been to <span class="highlighted-number">{{ cities_count|default_if_none:'0' }} cities</span> in <span class="highlighted-number">{{ country_count|default_if_none:'0' }} countries</span> (<a href="{% url 'core:events_map' %}">see them all on a map</a>).
                    </p>
                    <p>
                        A total of <span class="highlighted-number">{{ attendees_sum|default_if_none:'0' }} incredible women attended</span> events organized by members of our community.
                    </p>
                    <p><a href="{% url 'core:year_2015' %}">Read our Annual Report to learn about the impact we make »</a></p>
                </div>

               <div class="col-md-6">
                    <h2>Bring Django Girls to your city!</h2>
                    <p>Is there no Django Girls event in your city? You can help make it happen!</p>
                    <p>We open sourced the <a href="http://organize.djangogirls.org/">Organizer Manual</a> that provides you with all information required to organize Django Girls workshop. By volunteering to organize, you're joining a vibrant and supportive community of {{ organizers_count|default_if_none:'0' }} organizers all over the world!</p>
                    <p><a class="btn" href="{% url 'core:organize' %}">Apply to organize a workshop</a></p>
                </div>
            </div>
        </section>

        <section id="events">
            <div class="row">
                <div class="col-md-12">
                    <h2>
                        Upcoming events
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:icalendar' %}">ICAL</a>
                        <a class="ical btn btn-default btn-xs" href="{% url 'core:events_map' %}">MAP</a>
                    </h2>
                </div>
            </div>

            <div class="upcoming-events">
                <div class="row-container">
                    <div class="row">
                    {% for event in future_events %}
                        {% include 'includes/_event.html' with event=event %}
                        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                    {% endfor %}
                    </div>
                </div>
                <div class="show-more"><a href="javascript:;">Show all {{ future_events_count }} upcoming events »</a></div>
            </div>
        </section>

        <section id="story">
            <div class="row">
                <div class="col-md-6">
                    <h2>Badass Django Ladies</h2>
                    <p>Each week we try to introduce one badass lady who use Python or Django and highlight her work:</p>

                    <div class="row">
                    {% for story in stories %}
                        {% include 'includes/_story.html' with story=story %}
                    {% endfor %}
                    </div>

                    <p><a href="{% url 'core:stories' %}">Read all Django Stories »</a></p>
                </div>
                <div class="col-md-6">
                    <h2>Latest from our blog</h2>
                    {% for blog in blogposts %}
                    <a href="{{ blog.post_url }}" target="_blank" class="post-title">{{ blog.name }}</a>
                    <p class="post-content">{{ blog.content|striptags|truncatewords:25 }} <a href="{{ blog.post_url }}" target="_blank">Read all »</a></p>
                    {% endfor %}
                </div>
            </div>
        </section>

        <section id="support">
            <div class="row">
                <div class="col-md-6">
                    <h2>Support our work</h2>
                    <p>Django Girls is a volunteer run organization, and we depend on your support to make it happen.</p>
                    <p class="support-stats">
                        <span class="highlighted-number">${{ patreon_stats.amount_raised }}</span> of <span class="highlighted-number">${{ patreon_stats.GOAL }}</span> monthly goal pledged
                    </p>
                    <div class="support-bar">
                      <div class="pledge" style="width: {{ patreon_stats.percentage_of_goal }}%">{{ patreon_stats.percentage_of_goal }}%</div>
                    </div>
                    <a class="btn" href="http://patreon.com/djangogirls">Make a recurring donation on Patreon</a>
                    <p class="partnership">
                        You can also send us a one time donation with <a href="https://www.paypal.com/uk/webapps/mpp/search-cause?charityId=129929&s=3">Paypal Giving Funds</a>.
                        If you would like to discuss a bigger partnership, <a href="{% url 'core:contact' %}">please get in touch</a>.
                    </p>
                </div>

                 <div class="col-md-6">
                    <h2>Stay up to date!</h2>
                    <p>
                        Subscribe to Django Girls Dispatch to receive the latest and greatest from our community every two weeks, straight to your inbox!
                    </p>
                    <p>
                      <form action="http://test2975.createsend.com/t/i/s/tykhhd/" method="post" id="subForm" class="newsletter">
                          <input id="fieldEmail" name="cm-tykhhd-tykhhd" type="email" placeholder="you@reaweso.me" required />
                          <input type="submit" value="Subscribe" />
                      </form>
                    </p>
                    <p>
                        <a href="{% url 'core:newsletter' %}">See the Django Girls Dispatch archives »</a>
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <h2>Buy a t-shirt!</h2>
                </div>
                <div class="col-md-6">
                    <p>
                        Help us spread the word about Django Girls while supporting us!
                    </p>
                    <p>We now have three awesome designs for fitted and straight-cut t-shirts: <a href="https://store.djangogirls.org/collections/frontpage/products/this-is-what-a-programmer-looks-like">"This is What a Programmer Looks Like"</a>, <a href="https://store.djangogirls.org/collections/frontpage/products/fitted-code-like-a-girl-t-shirt">"Code like a Girl"</a> and <a href="https://store.djangogirls.org/collections/frontpage/products/fitted-django-girls-t-shirt"> Django Girls logo</a>.</p>
                    <p>
                         All proceeds will go to two new projects:
                        <ul>
                    <li>Django Girls Summit: a two day unconference where organizers could meet and share their experiences about Django Girls workshops.</li>
                    <li>Django Girls Organizer Starter Kit: a swag boxes for organizers full of stickers, buttons and tattoos!</li>
                        </ul>
                    </p>
                    <p><b>To celebrate the launch with us, you can use code OMGYAY! to get a discount of 15% for any order made until end of March!</b></p>

                    <p><a href="https://store.djangogirls.org/" class="btn">Get your t-shirt today!</a></p>

                </div>
                <div class="col-md-6">
                    <a href="https://store.djangogirls.org/">
                        <img src="{% static 'img/global/tshirt.png' %}" alt="Mint 'Code like a Girl' and cranberry 'This is what a programmer looks like' t-shirts."/>
                    </a>
                </div>
            </div>
            </section>

        <section id="supporters">
            <div class="row">
                <div class="col-md-12">
                    <h2>They already support us! 💕</h2>
                    <p>Those incredible companies made a pledge to diversity and are actively helping us to change the ratio in the tech industry. <br /> If you wish to join them, support us on <a href="https://www.patreon.com/djangogirls">Patreon</a> or <a href="{% url 'core:contact' %}">drop us a line</a>.</p>
                </div>
            </div>

            <div class="row">
              <div class="col-md-3">
                  <a href="https://www.elastic.co/">
                      <img src="{% static 'img/global/supporters/elastic.png' %}" alt="Elastic" />
                  </a>
              </div>
                <div class="col-md-3">
                    <a href="http://lincolnloop.com/">
                        <img src="{% static 'img/global/supporters/lincolnloop.png' %}" alt="Lincoln Loop" />
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="http://www.divio.ch/en/">
                        <img src="{% static 'img/global/supporters/divio.png' %}" alt="Divio" style="margin-top: 25px" />
                    </a>
                </div>
                <div class="col-md-3">
                    <a href="https://p.ota.to/jobs/">
                        <img src="{% static 'img/global/supporters/potato.svg' %}" alt="Potato" style="height: 120px;" />
                    </a>
                </div>
            </div>

            <div class="row">
              <div class="col-md-3">
                  <a href="http://pythonanywhere.com/">
                      <img src="{% static 'img/global/supporters/pythonanywhere.png' %}" alt="Python Anywhere" style="margin-top: 25px" />
                  </a>
              </div>
                <div class="col-md-3">
                    <a href="https://www.mailchimp.com/">
                        <img src="{% static 'img/global/supporters/mailchimp.png' %}" alt="Mailchimp" style="margin-top: 0px" />
                    </a>
                </div>
            </div>

        </section>

    </div>

{% endblock %}

templates/core/newsletter.html
{% extends 'global/base.html' %}
{% load staticfiles markdown_deux_tags %}

{% block title %}Django Girls Dispatch - Newsletter{% endblock %}

{% block content %}
    <div class="container without-background" id="flatpage">
          <div id="value" class="row">
              <div class="col-md-12">
                  <h1>Django Girls Dispatch</h1>

                  <p>
                      We're sending a biweekly newsletter to friends and strangers
                      who support us and are curious how we're doing. 
                  </p>
              </div>
          </div>
          <div class="row" style="margin-top: 20px">
              <div class="col-md-12">
                  <h2>Subscribe</h2>
                  
                  <p>
                      We don't send advertisements or spam, and we won't share your email with anyone. <br />
                      We just send a biweekly dispatch and awesome announcements about things we're proud of.
                  </p>
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="//djangogirls.us8.list-manage.com/subscribe/post?u=5a007b2dabdeddc350bdbbaed&amp;id=d278270e6f" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5a007b2dabdeddc350bdbbaed_d278270e6f" tabindex="-1" value=""></div>
    <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button">
    </div>
</form>
</div>

<!--End mc_embed_signup-->
              </div>
          </div>

        <div class="row display_archive">
            <div class="col-md-12">
                <h2>Past editions</h2>
                    <script language="javascript" src="//djangogirls.us8.list-manage.com/generate-js/?u=5a007b2dabdeddc350bdbbaed&fid=14473&show=10" type="text/javascript"></script>
                </div>
            </div>
        <div class="col-md-12">
          <div class="row newsletter-archive">
                  <script type="text/javascript" src="https://djangogirls.createsend.com/t/i/p/mtyuh/-1/1/0/1/0/"></script>
              </div>
          </div>
        </div>
{% endblock %}