core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^test-404/$', 'core.views.error404'),
    url(r'^events/$', views.events, name='events'),
    url(r'^events/map/$', views.events_map, name='events_map'),
    url(r'^events/calendar.ics$', views.events_ical, name='icalendar'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),
    url(r'^newsletter/$', views.newsletter, name='newsletter'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^foundation/$', views.foundation, name='foundation'),
    url(r'^foundation/governing-document/$', views.governing_document,
        name='foundation-governing-document'),
    url(r'^contribute/$', views.contribute, name='contribute'),
    url(r'^donate/$', views.donate, name='donate'),
    url(r'^2015/$', views.year_2015, name='year_2015'),
    url(r'^terms-conditions/$', views.terms_conditions, name='terms-conditions'),
    url(r'^privacy-cookies/$', views.privacy_cookies, name='privacy-cookies'),
    url(r'^workshop-box/$', views.workshop_box, name='workshop-box'),

    url(r'^(?P<city>[\w\d/]+)/$', views.event, name='event'),
    url(r'^$', views.index, name='index'),
]

djangogirls/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView


urlpatterns = [
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Admin link for password reset
    # See: https://github.com/darklow/django-suit/blob/92a745d72935622220eca80edfce779419c30094/suit/templates/admin/login.html#L61
    url(r'^admin/password_reset/$',
        RedirectView.as_view(url='/account/password_reset', permanent=True),
        name='admin_password_reset'),

    # Regular links:
    url(r'^community/', include('jobs.urls', namespace='jobs')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^account/', include('django.contrib.auth.urls')),
    url(r'', include('applications.urls', namespace='applications')),
    url(r'', include('core.urls', namespace='core')),
]

jobs/urls.py
from django.conf.urls import url

from jobs import views


urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^meetups$', views.meetups, name='meetups'),
    url(r'^job/(?P<id>\d+)$', views.job_details, name='job_details'),
    url(r'^confirm_submission$', views.confirm_submission,
        name='confirm_submission'),
    url(r'^meetup/(?P<id>\d+)$', views.meetup_details, name='meetup_details'),
    url(r'^job/new$', views.create_job, name='job_new'),
    url(r'^meetup/new$', views.create_meetup, name='meetup_new'),
]

jobs/models.py
from __future__ import unicode_literals
from datetime import timedelta

from django.db import models
from django.db.models import Value, BooleanField
from django.db.models.expressions import CombinedExpression, F
from django.db.models.functions import Coalesce, Now
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
from django.template.loader import get_template
from django.template import Context

from django_countries.fields import CountryField

from core.models import User

from jobs.community_mails import send_job_mail, send_meetup_mail


class Greater(CombinedExpression):
    def __init__(self, lhs, rhs):
        super(Greater, self).__init__(lhs, ">", rhs, output_field=BooleanField())


class PublishFlowManager(models.Manager):
    def get_queryset(self):
        """
        The queryset returns an additional field: not_expired which is True
        for posts with the expiration date in the future or not set
        and False if the expiration date is in the past
        """
        not_expired = Greater(F('expiration_date'), Now())

        return super(PublishFlowManager, self).get_queryset().annotate(
                not_expired=Coalesce(not_expired, Value(True))
        )


class VisiblePublishFlowManager(PublishFlowManager):
    def get_queryset(self):
        return super(VisiblePublishFlowManager, self).get_queryset().filter(
            review_status=PublishFlowModel.PUBLISHED,
            not_expired=True
        )


class PublishFlowModel(models.Model):
    """
    An abstract class model that handles all logic related to publishing
    an item that needs to be reviewed
    """
    OPEN = 'OPN'
    UNDER_REVIEW = 'URE'
    READY_TO_PUBLISH = 'RTP'
    REJECTED = 'REJ'
    PUBLISHED = 'PUB'
    STATUSES = (
        (OPEN, 'Open'),
        (UNDER_REVIEW, 'Under review'),
        (READY_TO_PUBLISH, 'Ready to publish'),
        (REJECTED, 'Rejected'),
        (PUBLISHED, 'Published'),
    )

    reviewer = models.ForeignKey(
        User,
        related_name="%(app_label)s_%(class)s_related",
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )
    review_status = models.CharField(max_length=3, choices=STATUSES, default=OPEN)
    message_to_organisation = models.TextField(
        blank=True,
        null=True,
        help_text="Write your message to the company/organisation here."
    )
    internal_comment = models.TextField(
        blank=True,
        null=True,
        help_text="Write your comments here. They won't be sent to "
                  "the company/organisation."
    )
    published_date = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    expiration_date = models.DateField(
        blank=True,
        null=True,
        help_text="Enter the date until which the post should be published. "
                  "By default, it is set to 60 days from posting."
    )

    objects = PublishFlowManager()
    visible_objects = VisiblePublishFlowManager()

    class Meta:
        abstract = True
        ordering = ['-published_date']

    def is_ready_to_publish(self):
        return self.review_status == self.READY_TO_PUBLISH

    def assign(self, user):
        assert self.review_status == self.OPEN
        self.reviewer = user
        self.review_status = self.UNDER_REVIEW
        self.save()

    def unassign(self):
        assert self.review_status == self.UNDER_REVIEW
        self.reviewer = None
        self.review_status = self.OPEN
        self.save()

    def accept(self):
        assert self.review_status == self.UNDER_REVIEW
        self.review_status = self.READY_TO_PUBLISH
        self.save()

    def reject(self):
        assert self.review_status in [self.UNDER_REVIEW, self.READY_TO_PUBLISH, self.PUBLISHED]
        self.review_status = self.REJECTED
        self.published_date = None
        self.save()
        subject = '{0} was rejected.'.format(self.title)
        model_name = self._meta.model_name
        context = Context({
                    'status': self.get_review_status_display(),
                    'option': model_name,
                    'message_to_organisation': self.message_to_organisation,
                })
        message_plain = get_template(
            'jobs/email_templates/status.txt').render(context)
        message_html = get_template(
            'jobs/email_templates/status.html').render(context)
        recipient = self.contact_email
        if model_name == 'job':
            send_job_mail(
                    subject,
                    message_plain,
                    message_html,
                    recipient
                )
        elif model_name == 'meetup':
            send_meetup_mail(
                subject,
                message_plain,
                message_html,
                recipient,
            )

    def restore(self, user):
        assert self.review_status == self.REJECTED
        self.reviewer = user
        self.review_status = self.UNDER_REVIEW
        self.save()

    def publish(self):
        assert self.is_ready_to_publish()
        self.published_date = timezone.now()
        # the line below covers the situation when there is no expiration date
        # set or when somebody wants to republish an expired post but
        # hasn't changed the expiration date
        if not self.expiration_date or self.expiration_date < self.published_date.date():
            self.expiration_date = self.published_date + timedelta(60)
        self.review_status = self.PUBLISHED
        self.save()
        subject = '{0} is now published.'.format(self.title)
        model_name = self._meta.model_name
        context = Context({
                    'status': self.get_review_status_display(),
                    'option': model_name,
                    'message_to_organisation': self.message_to_organisation,
                })
        message_plain = get_template(
            'jobs/email_templates/status.txt').render(context)
        message_html = get_template(
            'jobs/email_templates/status.html').render(context)
        recipient = self.contact_email
        if model_name == 'job':
            send_job_mail(
                    subject,
                    message_plain,
                    message_html,
                    recipient
                )
        elif model_name == 'meetup':
            send_meetup_mail(
                subject,
                message_plain,
                message_html,
                recipient,
            )


@python_2_unicode_compatible
class Job(PublishFlowModel):
    title = models.CharField(max_length=255)
    company = models.CharField(max_length=255)
    website = models.URLField(
        help_text="Link to your offer or company website.",
        blank=True,
        null=True
    )
    contact_email = models.EmailField(max_length=255)
    cities = models.CharField(max_length=255)
    state_province = models.CharField(max_length=255,
        help_text="If relevant, add the name of the state or province where the job is available.",
        blank=True,
        null=True,
    )
    country = CountryField()
    description = models.TextField()
    remote_work = models.BooleanField(
        default=False,
    )
    relocation = models.BooleanField(
        default=False,
    )

    class Meta(PublishFlowModel.Meta):
        unique_together = (("company", "title"),)

    def __str__(self):
        return "{0}, {1}".format(self.title, self.company)


@python_2_unicode_compatible
class Meetup(PublishFlowModel):

    MEETUP = 'MEET'
    CONFERENCE = 'CONF'
    WORKSHOP = 'WORK'
    MEETUP_TYPES = (
        (MEETUP, 'meetup'),
        (CONFERENCE, 'conference'),
        (WORKSHOP, 'workshop'),
    )

    title = models.CharField(max_length=255)
    organisation = models.CharField(
        max_length=255,
        blank=True,
        null=True,
    )
    meetup_type = models.CharField(
        max_length=4,
        choices=MEETUP_TYPES,
        default=MEETUP
    )
    contact_email = models.EmailField(max_length=255)
    website = models.URLField(
        help_text="Link to your meetup or organisation website.",
        blank=True,
        null=True
    )
    city = models.CharField(max_length=255)
    state_province = models.CharField(max_length=255,
        help_text="If relevant, add the name of the state or province where the meetup/event is happening.",
        blank=True,
        null=True
    )
    country = CountryField()
    description = models.TextField()
    is_recurring = models.BooleanField(
        default=False,
    )
    #TODO this field should be required if the is_recurring is True
    recurrence = models.CharField(
        max_length=255,
        blank=True,
        null=True,
        help_text="Provide details of recurrence if applicable."
    )
    meetup_start_date = models.DateTimeField(
        null=True,
        help_text="If this is a recurring meetup/event, please enter a start date.\
            Date format: YYYY-MM-DD"
    )
    meetup_end_date = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Date format: YYYY-MM-DD"
    )

    class Meta(PublishFlowModel.Meta):
        unique_together = (("title", "city"),)

    def __str__(self):
        return "{0}, {1}".format(self.title, self.city)

jobs/views.py
from django.utils import timezone

from django.shortcuts import render, get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.contrib import messages

from django.template.loader import get_template
from django.template import Context

from jobs.models import Job, Meetup
from jobs.forms import JobForm, MeetupForm
from jobs.community_mails import send_job_mail, send_meetup_mail


def main(request):
    job_offers = Job.visible_objects.all().order_by('-published_date')[:4]
    meetup_list = Meetup.visible_objects.all().order_by('-published_date')[:3]
    return render(
        request,
        'jobs/main.html',
        {
            'meetup_list': meetup_list,
            'job_offers': job_offers
            }
    )


def jobs(request):
    job_offers = Job.visible_objects.all()
    return render(
        request,
        'jobs/jobs.html',
        {
            'job_offers': job_offers,
        }
    )


def meetups(request):
    meetup_list = Meetup.visible_objects.all()
    return TemplateResponse(
        request,
        'jobs/meetups.html',
        {
            'meetup_list': meetup_list,
        }
    )


def job_details(request, id):
    queryset = Job.visible_objects.all()
    job = get_object_or_404(queryset, id=id)
    return TemplateResponse(
        request,
        'jobs/job_details.html',
        {
            'job': job,
        }
    )


def meetup_details(request, id):
    queryset = Meetup.visible_objects.all()
    meetup = get_object_or_404(queryset, id=id)
    return TemplateResponse(
        request,
        'jobs/meetup_details.html',
        {
            'meetup': meetup,
        }
    )


def confirm_submission(request):
    return TemplateResponse(
        request,
        'jobs/confirm_submission.html'
    )


def create_job(request):
    job_form = JobForm()
    success_message = 'Your job opportunity was added to our database, \
                    you will receive further information shortly.'
    if request.method == 'POST':
        job_form = JobForm(request.POST)
        if job_form.is_valid():
            new_job = job_form.save()
            messages.add_message(
                request,
                messages.INFO,
                success_message
            )
            subject = '{0} was submitted succesfully.'.format(new_job.title)
            context = Context({'option': new_job.title})
            message_plain = get_template(
            'jobs/email_templates/community_confirm.txt').render(context)
            message_html = get_template(
                'jobs/email_templates/community_confirm.html').render(context)
            recipient = new_job.contact_email
            send_job_mail(
                subject,
                message_plain,
                message_html,
                recipient
            )
            return redirect('jobs:confirm_submission')
    return TemplateResponse(
        request,
        'jobs/job_edit.html',
        {
            'form': job_form,
        }
    )


def create_meetup(request):
    meetup_form = MeetupForm()
    success_message = 'Your meetup was added to our database, \
                    you will receive further information shortly.'
    if request.method == 'POST':
        meetup_form = MeetupForm(request.POST)
        if meetup_form.is_valid():
            new_meetup = meetup_form.save()
            messages.add_message(
                request,
                messages.INFO,
                success_message
            )
            subject = '{0} was submitted succesfully.'.format(new_meetup.title)
            context = Context({'option': new_meetup.title})
            message_plain = get_template(
            'jobs/email_templates/community_confirm.txt').render(context)
            message_html = get_template(
                'jobs/email_templates/community_confirm.html').render(context)
            recipient = new_meetup.contact_email
            send_meetup_mail(
                subject,
                message_plain,
                message_html,
                recipient
            )
            return redirect('jobs:confirm_submission')
    return TemplateResponse(
        request,
        'jobs/meetup_edit.html',
        {
            'form': meetup_form,
        }
    )

templates/jobs/job_details.html
{% extends 'jobs/base.html' %}
{% load staticfiles %}

{% block content %}

<section id="job_details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                
                <ol class="breadcrumb">
                    <li><a href="{% url 'core:index' %}">Home</a></li>
                    <li><a href="{% url 'jobs:main' %}">Community</a></li>
                    <li><a href="{% url 'jobs:jobs' %}">Job opportunities</a></li>
                    <li class="active">{{ job.title }}</li>
                </ol>
                <div class="page-header">
                    <h3>{{ job.title }} <small>at {{ job.company }}</small></h3>
                </div>
                <div class="panel panel-feature-blue">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <div class="text-muted pull-right">
                            <p>Published on {{ job.published_date|date:'d F Y' }}</p>
                            <table class="table" id="job-table">
                                <tr>
                                    <td>Remote work</td>
                                    <td><strong>{{ job.remote_work|yesno }}</strong></td>
                                </tr>
                                <tr>
                                    <td>Relocation offered</td>
                                    <td><strong>{{ job.relocation|yesno }}</strong></td>
                                </tr>
                            </table>
                        </div>
                        <h4>Where</h4>
                        <p>{{ job.cities }} ({{ job.country }})</p>
                        <h4>Description</h4>
                        <p>{{ job.description|safe }}</p>
                        <h4>Contact</h4>
                        <p>{{ job.contact_email|urlize }}</p>
                        <p><a href="{{ job.website }}">view website</a></p>
                    </div>
                </div>

            </div> <!--.col-md-12-->
        </div> <!--.row-->
    </div> <!--.container-->
</section> <!--#job_details-->


{% endblock content %}

templates/jobs/job_edit.html
{% extends 'jobs/base.html' %}
{% load staticfiles %}
{% load jobs_tags %}

{% block extra_js %}
    {{ form.media }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
         <ol class="breadcrumb">
            <li><a href="{% url 'core:index' %}">Home</a></li>
            <li><a href="{% url 'jobs:main' %}">Community</a></li>
            <li><a href="{% url 'jobs:jobs' %}">Job opportunities</a></li>
            <li class="active">Add job opportunity</li>
        </ol>
        <div>
            <h2>
                Add job opportunity
            </h2>
            <hr/>
            <p>
                Adding a job opportunity on Django Girls website is free. Yay!
                Our website is visited by many enthusiastic beginner developers and we can help you reach them with your offer.
                However, all the opportunities listed here need to meet following requirements:
            </p>
            <ul>
                <li>The opportunity needs to be beginner-friendly - no experience required.</li>
                <li>The opportunity must not discriminate any gender.</li>
            </ul>
            <p>
                By submitting a job opportunity to us, you're demonstrating that you care about diversity in your workplace and in the tech community in general.
                Thank you!
            </p>
            <br/>
            <p class="text-info">
                Publishing a job opportunity here is free, however, Django Girls is a non-profit organisation
                with a mission to show more women how amazing programming is. We would appreciate it if you would
                consider <a href="https://www.patreon.com/djangogirls">making a donation through Patreon</a> to help us make a bigger impact.
            </p>
            <br/>
        </div>
            <div class="panel panel-feature-blue">
                <div class="panel-heading">
                    <h2>New job opportunity</h2>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal job-form" method="POST">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.errors %}
                                <div class="form-group has-error">
                                    <label class="col-sm-2 control-label">{{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}</label>
                                    <div class="controls col-sm-10">{{ field|addclass:"form-control" }}
                                        <p><span class="help-inline text-danger">
                                            {% for error in  field.errors %}{{ error }}{% endfor %}
                                        </span></p>
                                        <p class="help-inline text-danger"><small>{{ field.help_text }}</small></p>
                                    </div>
                                </div>
                            {% else %}
                                <div class="form-group">
                                    <label class="col-sm-2 control-label">{{ field.label }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}</label>
                                    <div class="controls col-sm-10">{{ field|addclass:"form-control" }}
                                        {% if field.help_text %}
                                            <p class="help-inline"><small>{{ field.help_text }}</small></p>
                                        {% endif %}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}

                        <div class="form-actions">
                            <button type="submit" class="save btn btn-blue" name="save">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/jobs/jobs.html
{% extends 'jobs/base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="container">
        <section id="jobs">
            <div class="row">
                <div class="col-md-12">
                    <ol class="breadcrumb">
                        <li><a href="{% url 'core:index' %}">Home</a></li>
                        <li><a href="{% url 'jobs:main' %}">Community</a></li>
                        <li class="active">Job opportunities</li>
                    </ol>
                    <h2>
                        Job opportunities
                    </h2>

                    <hr/>
                      {% include 'includes/_jobs_intro.html' %}

                    <p class="text-info">
                       On this page, we only list opportunities that require no experience from companies who
                       want to hire beginners and care about diversity.
                    </p>
                    <a class="btn btn-blue" href="{% url 'jobs:job_new' %}">Add opportunity</a>
                </div> <!--.col-md-12-->
            </div> <!--.row-->

            <div class="row">
                <div class="col-md-12">
                    <h3>Open opportunities</h3>
                    <table class="table table-striped">
                        <thead>
                            <th>Company</th>
                            <th>Job title</th>
                            <th>Location</th>
                            <th>Posted</th>
                        </thead>
                        <tbody>
                            {% for job in job_offers %}
                                <tr>
                                    <td>
                                        {{ job.company }}
                                    </td>
                                    <td>
                                        <a href="{% url 'jobs:job_details' id=job.id %}">
                                            {{ job.title }}
                                        </a>
                                    </td>
                                    <td>{{ job.cities }} ({{ job.country }})</td>
                                    <td>{{ job.published_date }}</td>
                                </tr>
                            {% empty %}
                                <tr>
                                    <td>There are no job opportunities at this moment.</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!--.col-md-12-->
            </div> <!--.row-->
        </section>
    </div> <!--.container-->

{% endblock %}

templates/jobs/main.html
{% extends 'jobs/base.html' %}
{% load staticfiles %}

{% block content %}

<section id="box-with-picture">
    <div class="black-canvas">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1>
                        You've already attended Django Girls event?
                    </h1>

                    <p>there is much more...</p>
                </div>
            </div>
        </div>
    </div>
</section>

<div class="container">
    <section id="community">
        <div class="row">
            <div class="col-md-12">
                 <ol class="breadcrumb">
                    <li><a href="{% url 'core:index' %}">Home</a></li>
                    <li class="active">Community</li>
                </ol>
                <h2>Django Girls Community</h2>

                <p>If you find yourself on this page, you probably recently completed the Django Girls tutorial — either at one of our workshops, at an event in your city or at home on your own.</p>
                <p>That’s awesome, congratulations! Time to meet the Django and Python community and make the next important step towards making development your daily job. Excited? We are!</p>
            </div>
        </div>
    </section>
    <section id="features">
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-feature-blue">
                    <div class="panel-heading">
                        <h3>Jobs</h3>
                    </div>
                    <div class="panel-body">
                          {% include 'includes/_jobs_intro.html' %}
                        <br/>
                        <h4>Recent opportunities:</h4>
                        <hr/>
                        {% if job_offers %}
                            {% for job in job_offers %}
                                {% include 'includes/_jobs.html' with job=job %}
                            {% endfor %}
                        {% else %}
                            <p>No job opportunities yet...</p>
                        {% endif %}
                            <a class="btn btn-blue btn-block" href="{% url 'jobs:jobs' %}">More...</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-feature-orange">
                    <div class="panel-heading">
                        <h3>Meetups</h3>
                    </div>
                    <div class="panel-body">
                          {% include 'includes/_meetups_intro.html' %}
                        <br/>
                        <h4>Recent meetups:</h4>
                        <hr/>
                        {% if meetup_list %}
                            {% for meetup in meetup_list %}
                                {% include 'includes/_meetups.html' with meetup=meetup %}
                            {% endfor %}
                        {% else %}
                            <p>No meetups yet...</p>
                        {% endif %}
                            <a class="btn btn-block" href="{% url 'jobs:meetups' %}">More...</a>
                    </div>
                </div>
            </div>

        </div>
    </section>
</div> <!--.container-->

{% endblock %}

templates/jobs/meetup_details.html
{% extends 'jobs/base.html' %}
{% load staticfiles %}

{% block content %}

<section id="meetup_details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <ol class="breadcrumb">
                    <li><a href="{% url 'core:index' %}">Home</a></li>
                    <li><a href="{% url 'jobs:main' %}">Community</a></li>
                    <li><a href="{% url 'jobs:meetups' %}">Meetups</a></li>
                    <li class="active">{{ meetup.title }}</li>
                </ol>
                <div class="page-header">
                    <h3>
                        {% if meetup.website %}
                            <a href="{{ meetup.website }}">{{ meetup.title }}</a>
                        {% else %}
                            {{ meetup.title }}
                        {% endif %}
                        <small>in {{ meetup.city }} ({{ meetup.country }})</small>
                    </h3>
                </div>
                <div class="panel panel-feature-orange">
                    <div class="panel-heading">
                    </div>
                    <div class="panel-body">
                        <div class="text-muted pull-right">
                            <p>{{ meetup.get_meetup_type_display }}</p>
                            <p>Published on {{ meetup.published_date|date:'d F Y' }}</p>
                        </div>
                        <h4>When</h4>
                        <p>
                            <strong>Begins:</strong> {{ meetup.meetup_start_date|date:"l, d F Y, f A" }}
                        </p>
                            {% if meetup.meetup_end_date %}
                                <p>
                                    <strong>Ends:</strong> {{ meetup.meetup_end_date|date:"l, d F Y, f A" }}
                                </p>
                            {% endif %}
                        <h4>Description</h4>
                        <p>{{ meetup.description|safe }}</p>
                        {% if meetup.is_recurring %}
                            <p><strong>This is a recurring event:</strong> {{ meetup.recurrence }}</p>
                        {% endif %}
                        {% if meetup.organisation %}
                            <h4>Organised by</h4>
                            <p>{{ meetup.organisation }}</p>
                        {% endif %}
                        <h4>Contact</h4>
                        <p>{{ meetup.contact_email }}</p>
                    </div>
                </div>


            </div> <!--.col-md-12-->
        </div> <!--.row-->
    </div> <!--.container-->
</section> <!--#meetup_details-->


{% endblock content %}